address: localhost
port: 8080
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/users
    username: user
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  session:
    storage-type: redis
  redis:
    timeout: 600
    host: 127.0.0.1
    port: 6379
  jwt:
    secret: govlepel@$&

server:
  port: 8080

