spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.24:5432/auth-db
    username: user
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  session:
    storage-type: redis
  redis:
    timeout: 600
    host: 192.168.0.24
    port: 6379
  jwt:
    secret: govlepel@$&

server:
  # ssl:
  #     key-store: classpath:keystore.p12
  #     key-store-password: 1234
  #     key-store-type: PKCS12
