address: localhost
port: 8080
spring:
  session:
    storage-type: redis
  redis:
    timeout: 600
    host: 172.18.0.1
    port: 6381
  jwt:
    secret: govlepel@$&


server:
  port: 8080
  ssl :
    key-store: classpath:keystore.p12
    key-store-password: 1234
    key-store-type: PKCS12
  