# 버전지정
version: "3.3" 

# 컨테이너 설정

networks: 
  spring-network:
    external: true

services: 
  voice-service:
    build: .
    image: voice
    restart: always
    networks:
      - spring-network
    entrypoint: ["bash", "-c"]
    ports:
      - 8082:8080
    command:
      - |
        sleep 15s
        java -jar voice.jar   