# 버전지정
version: "3.3" 

# 컨테이너 설정

networks: 
  spring-network:
    external: true

services: 
  chat-service:
    build: .
    image: chat
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://chat-database:3307/chat-db?useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5Dialect
      SPRING_SESSION_STORAGE_TYPE: redis
      SPRING_REDIS_HOST: chat-redis
      SPRING_REDIS_PORT: 6379

    depends_on:
      - chat-database
      - chat-redis
    restart: always
    networks:
      - spring-network
    entrypoint: ["bash", "-c"]
    command:
      - |
        sleep 20s
        java -jar chat.jar   

  chat-database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: chat-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 3307
    networks:
      - spring-network
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  
  chat-redis:
    image: redis:6.2.6
    networks:
      - spring-network
    command: [ "redis-server", "--protected-mode", "no" ]

  # nginx-service:
  #   image: nginx
  #   networks:
  #     - spring-network
  #   ports:
  #     - 81:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
    
    
