# 버전지정
version: "3.3" 

# 컨테이너 설정

networks: 
  spring-network:
    external: true

services: 
  chat-service:
    build: .
    image: chat
    restart: always
    networks:
      - spring-network
    entrypoint: ["bash", "-c"]
    ports:
      - 8081:8080
    command:
      - |
        sleep 20s
        java -jar chat.jar   
