# 버전지정
version: "3.3" 

# 컨테이너 설정

networks: 
  spring-network:
    external: true

services: 
  auth-service:
    build: .
    image: auth
    restart: always
    networks:
      - spring-network
    entrypoint: ["bash", "-c"]
    ports:
      - 8080:8080
    command:
      - |
        sleep 10s
        java -jar auth.jar   

