address: localhost
port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webRTC
    username: ds4ouj
    password: hong971220!
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: validate
  session:
    storage-type: redis
  redis:
    timeout: 600
    host: 127.0.0.1
    port: 6379
  jwt:
    secret: govlepel@$&

server:
  port: 8080
  # ssl:
  #   key-store: classpath:keystore.p12
  #   key-store-password: 1234
  #   key-store-type: PKCS12