# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: redis-slave CI

on:
  push: 
    branches: [ redis-slave ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build the Docker image
      run: docker build . --tag ds4ouj/redis-slave
    
    - name: Docker Push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/redis-slave

